modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Ran-Mewo/Censorship/issues"
license = "LGPL"

[[mods]]
modId = "censorship"
version = "${version}"
displayName = "Censorship"
authors = "Ran"
description = '''
A server-side mod that helps maintain chat civility by filtering inappropriate language and content.
This is a copy of the censorship used in the Distant Horizons discord server!
'''
#logoFile = ""

[[dependencies.censorship]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.censorship]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.censorship]]
modId = "configapi"
type = "required"
versionRange = "[1.21.4-2.4.1,)"
ordering = "NONE"
side = "SERVER"

[[mixins]]
config = "censorship.mixins.json"
